module.exports = {
	WEB_TITLE: 'Anya S3 File Manager',
	STORE_EVENT_PREFIX: 'STORE_EVENT:',
	STORE_KEYS: {
		IS_API_PROCESSING: 'IS_API_PROCESSING',
		DELETED_OBJECT_NOTIFICATION: 'OBJECT.DELETED',
	},
};
