module.exports = {
	ENVIRONMENT_MODE: {
		DEFAULT: 'default',
		STAGING: 'staging',
	},
	FRONTEND_OPERATION_CODE: {
		SHOW_OBJECT_DUPLICATED_ALERT: 'OBJECT.ALERTS.DUPLICATED.SHOW',
	},
	OBJECT_TYPE: {
		FOLDER: 1,
		FILE: 2,
	},
	STORAGE_CLASS: {
		STANDARD: 1,
		REDUCED_REDUNDANCY: 2,
		STANDARD_IA: 3,
		ONEZONE_IA: 4,
		INTELLIGENT_TIERING: 5,
		GLACIER: 6,
		DEEP_ARCHIVE: 7,
		OUTPOSTS: 8,
		GLACIER_IR: 9,
	},
};
