module.exports = {
	ENVIRONMENT_MODE: {
		DEFAULT: 'default',
		STAGING: 'staging',
	},
	FRONTEND_OPERATION_CODE: {
		SHOW_OBJECT_DUPLICATED_ALERT: 'OBJECT.ALERTS.DUPLICATED.SHOW',
	},
	FILE_TYPE: {
		FOLDER: 1,
		FILE: 2,
	},
};
