module.exports = {
	ENVIRONMENT_MODE: {
		DEFAULT: 'default',
		STAGING: 'staging',
	},
	FRONTEND_OPERATION_CODE: {
		SHOW_TAG_DUPLICATED_ALERT: 'TAG.ALERTS.DUPLICATED.SHOW',
		SHOW_TAG_OVER_LIMIT_ALERT: 'TAG.ALERTS.OVER-LIMIT.SHOW',
	},
	FILE_TYPE: {
		FOLDER: 1,
		FILE: 2,
	},
};
